[package]
name = "gaemboi"
version = "0.1.0"
edition = "2021"

[dependencies]
rfd = "0.12.1"
egui_sdl2_gl = "0.27.1"
sdl2 = { version = "0.36.0", features = ["bundled", "static-link"] }
image = "0.25.2"
lewton = "0.10.2"
