#[allow(clippy::upper_case_acronyms)]
#[allow(non_camel_case_types)]
#[derive(Debug)]
pub enum Mnemonic {
    NOP,
    RST(u16),
    JP_nn,
    CP_n,
    CALL_nn,
    CALL_c_nn(Flag),
    CALL_nc_nn(Flag),
    AND_n,
    ADD_r(Target),
    INC_r(Target),
    INC_rr(Target),
    DEC_rr(Target),
    POP_rr(Target),
    POP_af,
    SUB_n,
    OR_r(Target),
    XOR_r(Target),
    LD_r_r(Target, Target),
    LD_r_n(Target),
    LD_a_nn,
    LD_a_hl_plus,
    LD_rr_r(Target, Target),
    LD_rr_nn(Target),
    LD_r_rr(Target, Target),
    LD_nn_a,
    LDH_n_a,
    LDH_a_n,
    LD_sp_nn,
    LD_sp_hl,
    JR_c_e(Flag),
    JR_nc_e(Flag),
    JR_e,
    PUSH_rr(Target),
    DisableInterrupt,
    RET,
    RET_c(Flag),
    RET_nc(Flag),
    Prefix,
    RES_b_r(u8, Target),
}

#[derive(Debug)]
pub enum Target {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    AF,
    BC,
    DE,
    HL,
}

#[derive(Debug)]
pub enum Flag {
    Z,
    N,
    H,
    C,
}

pub struct Instruction {
    pub mnemonic: Mnemonic,
    pub length: u16,
    m_cycles: u8,
}

impl Instruction {
    fn new(mnemonic: Mnemonic, length: u16, m_cycles: u8) -> Self {
        Self {
            mnemonic,
            length,
            m_cycles,
        }
    }

    pub fn from_byte(value: u8) -> Self {
        match value {
            0x00 => Instruction::new(Mnemonic::NOP, 1, 1),
            0x01 => Instruction::new(Mnemonic::LD_rr_nn(Target::BC), 3, 3),
            0x02 => Instruction::new(Mnemonic::LD_rr_r(Target::BC, Target::A), 1, 2),
            0x03 => Instruction::new(Mnemonic::INC_rr(Target::BC), 1, 2),
            0x04 => Instruction::new(Mnemonic::INC_r(Target::B), 1, 1),
            0x0B => Instruction::new(Mnemonic::DEC_rr(Target::BC), 1, 2),
            0x0E => Instruction::new(Mnemonic::LD_r_n(Target::C), 2, 2),
            0x12 => Instruction::new(Mnemonic::LD_rr_r(Target::DE, Target::A), 1, 2),
            0x13 => Instruction::new(Mnemonic::INC_rr(Target::DE), 1, 2),
            0x18 => Instruction::new(Mnemonic::JR_e, 2, 3),
            0x1A => Instruction::new(Mnemonic::LD_r_rr(Target::A, Target::DE), 1, 2),
            0x1E => Instruction::new(Mnemonic::LD_r_n(Target::E), 2, 2),
            0x20 => Instruction::new(Mnemonic::JR_nc_e(Flag::Z), 2, 3),
            0x21 => Instruction::new(Mnemonic::LD_rr_nn(Target::HL), 3, 3),
            0x23 => Instruction::new(Mnemonic::INC_rr(Target::HL), 1, 2),
            0x26 => Instruction::new(Mnemonic::LD_r_n(Target::H), 2, 2),
            0x28 => Instruction::new(Mnemonic::JR_c_e(Flag::Z), 2, 2),
            0x2A => Instruction::new(Mnemonic::LD_a_hl_plus, 1, 2),
            0x2E => Instruction::new(Mnemonic::LD_r_n(Target::L), 2, 2),
            0x30 => Instruction::new(Mnemonic::JR_nc_e(Flag::C), 2, 3),
            0x31 => Instruction::new(Mnemonic::LD_sp_nn, 3, 3),
            0x3C => Instruction::new(Mnemonic::INC_r(Target::A), 1, 1),
            0x3E => Instruction::new(Mnemonic::LD_r_n(Target::A), 2, 2),
            0x40 => Instruction::new(Mnemonic::LD_r_r(Target::B, Target::B), 1, 1),
            0x41 => Instruction::new(Mnemonic::LD_r_r(Target::B, Target::C), 1, 1),
            0x42 => Instruction::new(Mnemonic::LD_r_r(Target::B, Target::D), 1, 1),
            0x43 => Instruction::new(Mnemonic::LD_r_r(Target::B, Target::E), 1, 1),
            0x44 => Instruction::new(Mnemonic::LD_r_r(Target::B, Target::H), 1, 1),
            0x45 => Instruction::new(Mnemonic::LD_r_r(Target::B, Target::L), 1, 1),
            0x46 => Instruction::new(Mnemonic::LD_r_rr(Target::B, Target::HL), 1, 2),
            0x47 => Instruction::new(Mnemonic::LD_r_r(Target::B, Target::A), 1, 1),
            0x48 => Instruction::new(Mnemonic::LD_r_r(Target::C, Target::B), 1, 1),
            0x49 => Instruction::new(Mnemonic::LD_r_r(Target::C, Target::C), 1, 1),
            0x4A => Instruction::new(Mnemonic::LD_r_r(Target::C, Target::D), 1, 1),
            0x4B => Instruction::new(Mnemonic::LD_r_r(Target::C, Target::E), 1, 1),
            0x4C => Instruction::new(Mnemonic::LD_r_r(Target::C, Target::H), 1, 1),
            0x4D => Instruction::new(Mnemonic::LD_r_r(Target::C, Target::L), 1, 1),
            0x4E => Instruction::new(Mnemonic::LD_r_rr(Target::C, Target::HL), 1, 2),
            0x4F => Instruction::new(Mnemonic::LD_r_r(Target::C, Target::A), 1, 1),
            0x50 => Instruction::new(Mnemonic::LD_r_r(Target::D, Target::B), 1, 1),
            0x51 => Instruction::new(Mnemonic::LD_r_r(Target::D, Target::C), 1, 1),
            0x52 => Instruction::new(Mnemonic::LD_r_r(Target::D, Target::D), 1, 1),
            0x53 => Instruction::new(Mnemonic::LD_r_r(Target::D, Target::E), 1, 1),
            0x54 => Instruction::new(Mnemonic::LD_r_r(Target::D, Target::H), 1, 1),
            0x55 => Instruction::new(Mnemonic::LD_r_r(Target::D, Target::L), 1, 1),
            0x56 => Instruction::new(Mnemonic::LD_r_rr(Target::D, Target::HL), 1, 2),
            0x57 => Instruction::new(Mnemonic::LD_r_r(Target::D, Target::A), 1, 1),
            0x58 => Instruction::new(Mnemonic::LD_r_r(Target::E, Target::B), 1, 1),
            0x59 => Instruction::new(Mnemonic::LD_r_r(Target::E, Target::C), 1, 1),
            0x5A => Instruction::new(Mnemonic::LD_r_r(Target::E, Target::D), 1, 1),
            0x5B => Instruction::new(Mnemonic::LD_r_r(Target::E, Target::E), 1, 1),
            0x5C => Instruction::new(Mnemonic::LD_r_r(Target::E, Target::H), 1, 1),
            0x5D => Instruction::new(Mnemonic::LD_r_r(Target::E, Target::L), 1, 1),
            0x5E => Instruction::new(Mnemonic::LD_r_rr(Target::E, Target::HL), 1, 2),
            0x5F => Instruction::new(Mnemonic::LD_r_r(Target::E, Target::A), 1, 1),
            0x60 => Instruction::new(Mnemonic::LD_r_r(Target::H, Target::B), 1, 1),
            0x61 => Instruction::new(Mnemonic::LD_r_r(Target::H, Target::C), 1, 1),
            0x62 => Instruction::new(Mnemonic::LD_r_r(Target::H, Target::D), 1, 1),
            0x63 => Instruction::new(Mnemonic::LD_r_r(Target::H, Target::E), 1, 1),
            0x64 => Instruction::new(Mnemonic::LD_r_r(Target::H, Target::H), 1, 1),
            0x65 => Instruction::new(Mnemonic::LD_r_r(Target::H, Target::L), 1, 1),
            0x66 => Instruction::new(Mnemonic::LD_r_rr(Target::H, Target::HL), 1, 2),
            0x67 => Instruction::new(Mnemonic::LD_r_r(Target::H, Target::A), 1, 1),
            0x68 => Instruction::new(Mnemonic::LD_r_r(Target::L, Target::B), 1, 1),
            0x69 => Instruction::new(Mnemonic::LD_r_r(Target::L, Target::C), 1, 1),
            0x6A => Instruction::new(Mnemonic::LD_r_r(Target::L, Target::D), 1, 1),
            0x6B => Instruction::new(Mnemonic::LD_r_r(Target::L, Target::E), 1, 1),
            0x6C => Instruction::new(Mnemonic::LD_r_r(Target::L, Target::H), 1, 1),
            0x6D => Instruction::new(Mnemonic::LD_r_r(Target::L, Target::L), 1, 1),
            0x6E => Instruction::new(Mnemonic::LD_r_rr(Target::L, Target::HL), 1, 2),
            0x6F => Instruction::new(Mnemonic::LD_r_r(Target::L, Target::A), 1, 1),
            0x70 => Instruction::new(Mnemonic::LD_rr_r(Target::HL, Target::B), 1, 2),
            0x71 => Instruction::new(Mnemonic::LD_rr_r(Target::HL, Target::C), 1, 2),
            0x72 => Instruction::new(Mnemonic::LD_rr_r(Target::HL, Target::D), 1, 2),
            0x73 => Instruction::new(Mnemonic::LD_rr_r(Target::HL, Target::E), 1, 2),
            0x74 => Instruction::new(Mnemonic::LD_rr_r(Target::HL, Target::H), 1, 2),
            0x75 => Instruction::new(Mnemonic::LD_rr_r(Target::HL, Target::L), 1, 2),
            0x77 => Instruction::new(Mnemonic::LD_rr_r(Target::HL, Target::A), 1, 2),
            0x78 => Instruction::new(Mnemonic::LD_r_r(Target::A, Target::B), 1, 1),
            0x79 => Instruction::new(Mnemonic::LD_r_r(Target::A, Target::C), 1, 1),
            0x7A => Instruction::new(Mnemonic::LD_r_r(Target::A, Target::D), 1, 1),
            0x7B => Instruction::new(Mnemonic::LD_r_r(Target::A, Target::E), 1, 1),
            0x7C => Instruction::new(Mnemonic::LD_r_r(Target::A, Target::H), 1, 1),
            0x7D => Instruction::new(Mnemonic::LD_r_r(Target::A, Target::L), 1, 1),
            0x7E => Instruction::new(Mnemonic::LD_r_rr(Target::A, Target::HL), 1, 2),
            0x7F => Instruction::new(Mnemonic::LD_r_r(Target::A, Target::A), 1, 1),
            0x80 => Instruction::new(Mnemonic::ADD_r(Target::B), 1, 1),
            0xA8 => Instruction::new(Mnemonic::XOR_r(Target::B), 1, 1),
            0xA9 => Instruction::new(Mnemonic::XOR_r(Target::C), 1, 1),
            0xAA => Instruction::new(Mnemonic::XOR_r(Target::D), 1, 1),
            0xAB => Instruction::new(Mnemonic::XOR_r(Target::E), 1, 1),
            0xAC => Instruction::new(Mnemonic::XOR_r(Target::H), 1, 1),
            0xAD => Instruction::new(Mnemonic::XOR_r(Target::L), 1, 1),
            0xAF => Instruction::new(Mnemonic::XOR_r(Target::A), 1, 1),
            0xB1 => Instruction::new(Mnemonic::OR_r(Target::C), 1, 1),
            0xC0 => Instruction::new(Mnemonic::RET_nc(Flag::Z), 1, 2),
            0xC1 => Instruction::new(Mnemonic::POP_rr(Target::BC), 1, 3),
            0xC3 => Instruction::new(Mnemonic::JP_nn, 3, 4),
            0xC4 => Instruction::new(Mnemonic::CALL_nc_nn(Flag::Z), 3, 3),
            0xC5 => Instruction::new(Mnemonic::PUSH_rr(Target::BC), 1, 4),
            0xC8 => Instruction::new(Mnemonic::RET_c(Flag::Z), 1, 2),
            0xC9 => Instruction::new(Mnemonic::RET, 1, 4),
            0xCB => Instruction::new(Mnemonic::Prefix, 1, 1),
            0xCC => Instruction::new(Mnemonic::CALL_c_nn(Flag::Z), 3, 3),
            0xCD => Instruction::new(Mnemonic::CALL_nn, 3, 6),
            0xCF => Instruction::new(Mnemonic::RST(0x0008), 1, 4),
            0xD6 => Instruction::new(Mnemonic::SUB_n, 2, 2),
            0xDF => Instruction::new(Mnemonic::RST(0x0018), 1, 4),
            0xE0 => Instruction::new(Mnemonic::LDH_n_a, 2, 3),
            0xE1 => Instruction::new(Mnemonic::POP_rr(Target::HL), 1, 3),
            0xE5 => Instruction::new(Mnemonic::PUSH_rr(Target::HL), 1, 4),
            0xE6 => Instruction::new(Mnemonic::AND_n, 2, 2),
            0xEA => Instruction::new(Mnemonic::LD_nn_a, 3, 4),
            0xEF => Instruction::new(Mnemonic::RST(0x0028), 1, 4),
            0xF0 => Instruction::new(Mnemonic::LDH_a_n, 2, 3),
            0xF1 => Instruction::new(Mnemonic::POP_af, 1, 3),
            0xF3 => Instruction::new(Mnemonic::DisableInterrupt, 1, 1),
            0xF5 => Instruction::new(Mnemonic::PUSH_rr(Target::AF), 1, 4),
            0xF9 => Instruction::new(Mnemonic::LD_sp_hl, 1, 2),
            0xFA => Instruction::new(Mnemonic::LD_a_nn, 3, 4),
            0xFE => Instruction::new(Mnemonic::CP_n, 2, 2),
            0xFF => Instruction::new(Mnemonic::RST(0x0038), 1, 4),
            _ => panic!("Instruction for byte {:#X} not implemented.", value),
        }
    }

    pub fn from_prefix(value: u8) -> Self {
        match value {
            0x87 => Instruction::new(Mnemonic::RES_b_r(0, Target::A), 2, 2),
            _ => panic!("PREFIX Instruction for byte {:#X} not implemented.", value),
        }
    }
}
